name: Team3 Testing

on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Compile Java Code and Test
        working-directory: ./Projects/P1
        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
  
  TestPacManMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Testing TestPacManMove.java
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" tests/TestPacManMove.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
  
  TestGhostMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Testing TestGhostMove.java
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" tests/TestGhostMove.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
  
  TestMapGetLoc:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Testing TestMapGetLoc.java
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" tests/TestMapGetLoc.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc
  
  TestAttack:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Testing TestAttack.java
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" tests/TestAttack.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack
  
  TestMapEatCookie:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Testing TestMapEatCookie.java
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" tests/TestMapEatCookie.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie

  TestConsume:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      - uses: actions/checkout@v3

      - name: Testing TestConsume.java
        working-directory: ./Projects/P1
        run: |
          javac -cp "src/" src/*.java
          javac -cp "tests/junit-4.10.jar:src/:tests/" tests/TestConsume.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume
          